### ISSUE TITLE
[Request] Add TuBaTool

### ISSUE THREAD

**Issue by IsaacWangTT** [Ryanjiena/scoop-apps#168]
### Package Name

TuBaTool

### Latest version

2022.01

### Description

DIY爱好者的必备工具合集

### Homepage

http://www.tbtool.cn/

### License

Freeware

### Graphical interface

Yes

### Portable version

Yes

### Some indication of popularity/repute

https://www.ghxi.com/tbgjx.html

### Download link(s)

```powershell
https://download.tualatin.club/图吧工具箱2022.01绿色版自动解压程序.exe
```

**Comment by Ryanjiena** [comment]
https://github.com/Ryanjiena/scoop-apps/blob/master/bucket/tbtool.json
