### ISSUE TITLE
typoraCracker bug

### ISSUE THREAD

**Issue by chriscp-cat** [Ryanjiena/scoop-apps#172]
卸载脚本有问题  卸载的时候   我的scoop安装信息为  scoop-install.json,scoop-manifest.json 这两个文件
```if (-not $env:SCOOP_APPS) { $env:SCOOP_APPS = \"$env:SCOOP\\apps\" } ```
这个也没加

**Comment by JaimeZeng** [comment]
你说的是我昨天更新的 typoracrack 吗😂

**Comment by JaimeZeng** [comment]
那个包安装后应该是app.asar, install.json, manifest.json 三个文件

**Comment by chriscp-cat** [comment]
我安装的那个分支版本  scoop-install.json  scoop-manifest.json

**Comment by chriscp-cat** [comment]
Shovel  就是这两个

**Comment by Ryanjiena** [comment]
环境变量的问题我直接使用 `$env:SCOOP\apps` 了

**Comment by Ryanjiena** [comment]
我本地测试了，安装后是三个文件

![image](https://user-images.githubusercontent.com/43134606/161191727-659ef7c3-f6e2-4100-bdf8-6704e22a7aa9.png)

**Comment by chriscp-cat** [comment]
我用的 Shovel  ....  就是scoop-install.json 和scoop-manifest.json   
![image](https://user-images.githubusercontent.com/68489543/161192015-e42b745c-627e-4288-9a2b-408ae328367d.png)

**Comment by Ryanjiena** [comment]
> 我用的 Shovel .... 就是scoop-install.json 和scoop-manifest.json ![image](https://user-images.githubusercontent.com/68489543/161192015-e42b745c-627e-4288-9a2b-408ae328367d.png)

你这个不是有 app.asar 文件吗……

**Comment by Ryanjiena** [comment]
哦，我理解错了，现在应该没问题了吧😂

**Comment by chriscp-cat** [comment]
额  不是还没改吗  那个排除文件那里我看还是install.json和manifest.json

**Comment by JaimeZeng** [comment]
刚去吃饭了，现在应该好了吧

**Comment by chriscp-cat** [comment]
应该ok了
