### ISSUE TITLE
为什么带cn的clash包没了

### ISSUE THREAD

**Issue by chriscp-cat** [Ryanjiena/scoop-apps#173]
如题

**Comment by JaimeZeng** [comment]
在这个仓库里 https://ryanjie.coding.net/public/scoop/scoop-apps/git/files

**Comment by Ryanjiena** [comment]
我又重新添加了 `clash-for-windows-portable-cn` 包，之前的 cn 包只是使用 github mirror 下载 release 文件，现在的 cn 包更符合包名

**Comment by Ryanjiena** [comment]
使用 github mirror 的包可以使用 coding 的仓库（包里关于 github release 的文件全部使用 [`github mirror`](https://www.github.do/) 下载）

**Comment by chriscp-cat** [comment]
行吧  但是其实只有这一个包我需要 加速 其他的我都用的代理 反而用镜像站下载不了

**Comment by Ryanjiena** [comment]
![image](https://user-images.githubusercontent.com/43134606/161412860-00ccf3fe-5df0-499f-bd3f-79d31e207268.png)

应该是你代理的问题吧，我本地目前使用 coding 的，使用代理后可以正常下载……

**Comment by chriscp-cat** [comment]
啊  不太清楚

**Comment by Ryanjiena** [comment]
> 啊 不太清楚

点击图片新标签页查看就行（另外，你是一直 github 在线吗😂，直接秒回……）

**Comment by chriscp-cat** [comment]
因为我绑定的qq邮箱  我邮箱会收到消息的
