### ISSUE TITLE
[Bug] KMS-VL-ALL-AIO

### ISSUE THREAD

**Issue by RnYi** [Ryanjiena/scoop-apps#181]
### Package Name

KMS-VL-ALL-AIO

### Current Behaviour

cannot extract the .7z file because the password has been changed to 2022

### Expected Behaviour

 extract the .7z file

### Additional context/output

```powershell
It's not nessasary
```

### Possible Solution

```powershell
update password in the manifest
```

### Windows version

Windows 10

### OS architecture

64bit

### PowerShell Version

7.2.2

**Comment by JaimeZeng** [comment]
You are right. Thank you for reporting.
