### ISSUE TITLE
SogouInput-lite 的安装参数问题

### ISSUE THREAD

**Issue by wordpure** [Ryanjiena/scoop-apps#193]
[423Down 精简版](https://www.423down.com/587.html)的搜狗输入法，[安装参数](https://github.com/Ryanjiena/scoop-apps/blob/d0d474bd86e29e2608d98bc1cee83c8350de639e/bucket/SogouInput-lite.json#L27)加上 `/S` 时会跳过组件选择界面，只安装主程序。

![图片](https://user-images.githubusercontent.com/68013962/163755864-ab36e097-5299-4a71-9ee8-1bd8dc948dd6.png)

另外 `/S` 和 `/D` 好像是互斥的😂。

![图片](https://user-images.githubusercontent.com/68013962/163755544-7cecef9b-2f38-401f-b52f-3fc7ae5c1d32.png)

![图片](https://user-images.githubusercontent.com/68013962/163755570-a46ad27d-80ef-49b7-a704-5950247ab9ff.png)

**Comment by JaimeZeng** [comment]
我的锅，但是好像看眼花了😂...

**Comment by JaimeZeng** [comment]
已经修改。另外，之前的包名有点混乱，也一并修改了

https://github.com/Ryanjiena/scoop-apps/blob/5619c795a94a67ccadd9f9335129609474ea4e23/bucket/SogouInput-zd423.json#L26-L27

**Comment by wordpure** [comment]
可以了，感谢大佬。
