### ISSUE TITLE
[Request] Add WebView2

### ISSUE THREAD

**Issue by wordpure** [Ryanjiena/scoop-apps#205]
### Package Name

WebView2

### Latest version

100.0.1185.44

### Description

一种运行时设置，用于使用 Edge 引擎将 Web 功能呈现给桌面应用程序。 WebView2 允许开发人员直接在他们自己的应用程序中嵌入和显示Web 内容，包括 JavaScript、HTML 和CSS。

### Homepage

https://developer.microsoft.com/zh-CN/microsoft-edge/webview2/

### License

Unknown

### Graphical interface

No

### Portable version

No

### Some indication of popularity/repute

略

### Download link(s)

```powershell
https://developer.microsoft.com/zh-CN/microsoft-edge/webview2/#download-section
```

**Comment by JaimeZeng** [comment]
这个 windows 10/11 系统自带呀......

![Uploading image.png…]()

**Comment by wordpure** [comment]
不好意思，之前 Windows 10 还没有带 WebView2，我电脑上都是自己装的，升到 Windows11 之后出于惯性也手动下载安装，完全没发现系统自带了😂
